### ISSUE TITLE
Different log types light vs quiet

### ISSUE THREAD

**Issue by daniejstriata** [sophos/Sophos-Central-SIEM-Integration#5]
Different log types are grouped together but the explanation is not 100%. Can this be better explained in the Read.me?

'--light', - It is not apparent what will not be logged using this option
'--quiet', - It is not apparent what will not be logged using this option
 
will it be possible to better explain the two? What is the difference between light and quiet?

If I only want to log problems like malware detected, devices not compliant, or bad websites visited will light be enough?

**Comment by daniejstriata** [comment]
I see now that '--quiet', is to suppress the siem.py script from creating ouput and not related to the import of different log types.

**Comment by jberkers42** [comment]
A quick peruse of the siem.py code indicates taht the following "Noisy Event Types" are suppressed when you choose the --light option:

`
NOISY_EVENTTYPES = ['Event::Endpoint::NonCompliant',
                    'Event::Endpoint::Compliant',
                    'Event::Endpoint::Device::AlertedOnly',
                    'Event::Endpoint::UpdateFailure',
                    'Event::Endpoint::SavScanComplete',
                    'Event::Endpoint::Application::Allowed',
                    'Event::Endpoint::UpdateSuccess',
                    'Event::Endpoint::WebControlViolation',
                    'Event::Endpoint::WebFilteringBlocked']`

Hope that helps, and that someone else responds to my issue...

**Comment by 53686f63636f** [comment]
What's your issue exactly? I've worked pretty hard getting the alerts I
want into my siem.

If the issue is that light mode gets rid of alerts you want you can edit
the py code to better suite your needs

On Aug 7, 2017 1:43 AM, "John Berkers" <notifications@github.com> wrote:

A quick peruse of the siem.py code indicates taht the following "Noisy
Event Types" are suppressed when you choose the --light option:

NOISY_EVENTTYPES = ['Event::Endpoint::NonCompliant',
'Event::Endpoint::Compliant', 'Event::Endpoint::Device::AlertedOnly',
'Event::Endpoint::UpdateFailure', 'Event::Endpoint::SavScanComplete',
'Event::Endpoint::Application::Allowed', 'Event::Endpoint::UpdateSuccess',
'Event::Endpoint::WebControlViolation', 'Event::Endpoint::
WebFilteringBlocked']

Hope that helps, and that someone else responds to my issue...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sophos/Sophos-Central-SIEM-Integration/issues/5#issuecomment-320605489>,
or mute the thread

**Comment by keeely** [comment]
The code should be considered demo code that you modify to suit your needs.  The problem is that we have no easy way of testing the code because customers can use it with any number of SIEM solutions.  We are loosely trying to satisfy the needs of a Splunk environment.
